### ISSUE TITLE
Log to File

### ISSUE THREAD

**Issue by Nubber99** [ihtfw/Logazmic#5]
It would be great to have a log to file option, where the number,size and location of the logfiles could be specified.

**Comment by ihtfw** [comment]
You want to save current log view to file? i.e. you are receiveing log items using TCP and then want to save them?

**Comment by Nubber99** [comment]
Effectively, yes. I'd like to be able to save each logged message to a file, and have some kind of file rotation to stop the files from getting too big and filling up the disk, as no-one is likely to look at the PC for many months. There's a similar argument to be made concernig the display - limiting the number of displayed messages is a good idea, otherwise you'd run out of memory.

**Comment by ihtfw** [comment]
For your case you should configure NLog in your application to do this.

Save to file: https://github.com/nlog/NLog/wiki/File-target
**maxArchiveFiles** - Maximum number of archive files that should be kept. If maxArchiveFiles is less or equal to 0, old files aren't deleted
**maxArchiveFiles** - Maximum number of archive files that should be kept. If maxArchiveFiles is less or equal to 0, old files aren't deleted
**archiveAboveSize** - Size in bytes above which log files will be automatically archived

Logazmic is viewer, so it's not design to be run for monthes. It's designed to open existing log files and for real time logging.

**Comment by Nubber99** [comment]
I know about the logfiles for each individual application. As we have quite a few apps logging to a central viewer, it's better if we have a single logfile, because then it's easier to see what happened in chronological order. However if Logazmic isn't intended to do that, I'll look elsewhere. Thanks anyway.

**Comment by ihtfw** [comment]
Oh. Get it. You can write simple console app, that would listen and save logs to files and use all NLog configuration power to control them in one place.
