### ISSUE TITLE
[Question] Add parser to Analogy Log Viewer?

### ISSUE THREAD

**Issue by LiorBanai** [ihtfw/Logazmic#6]
Hi,
Do you mind if I add your parser to my log viewer at https://github.com/Analogy-LogViewer/Analogy.LogViewer
and
https://github.com/Analogy-LogViewer/Analogy.LogViewer.NLog

**Comment by ihtfw** [comment]
Hi,
Great project! Sure, reuse code.

**Comment by LiorBanai** [comment]
Just an update.
With your parsers and Core folder I was able to Create a offline (files) parsers.
I plan to add the real time (tcp/upd) later.
Thanks for creating the heavy work of parsers and logics 👍 

you can see the new project at:
https://github.com/Analogy-LogViewer/Analogy.LogViewer.Log4jXml

**Comment by ihtfw** [comment]
Awesome! I'm happy that my code fits your needs =)
